name: tadawebsolutions
favicon: null
layout_spectrum: 0.29025106923654675
typography_spectrum: 0.7715815505944192
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.08785357396118343
  lightness: 0.4040670287795365
  saturation: 0.2801179711241275
  rhythmicContrast: 0.48212483641691506
purpose: []
